# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
       MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts: # store the uberjar as an artifact
          path: target/SpringBootStandAloneExample-1.0.0.jar
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: copy to S3
          command: aws s3 target/SpringBootStandAloneExample-1.0.0.jar s3://circle-production-static-site/docs/ --delete